### ISSUE TITLE
KeyError: 15630

### ISSUE THREAD

**Issue by sarchernz** [ccrook/QGIS-Contour-Plugin#2]
Hi Chris. I'm using the plugin with QGIS 2.0.1 to process some lidar data and have this error message that pops up with the following information:

An error has occured while executing Python code:

Traceback (most recent call last):
  File "C:\Users\Steven/.qgis2/python/plugins\contour\contour.py", line 367, in accept
    self.makeContours()
  File "C:\Users\Steven/.qgis2/python/plugins\contour\contour.py", line 577, in makeContours
    lines = self.computeContours()
  File "C:\Users\Steven/.qgis2/python/plugins\contour\contour.py", line 621, in computeContours
    cs = plt.tricontour(x, y, z, levels, extend=extend)
  File "C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\matplotlib\pyplot.py", line 3090, in tricontour
    ret = ax.tricontour(_args, *_kwargs)
  File "C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\matplotlib\axes.py", line 8922, in tricontour
    return mtri.tricontour(self, _args, *_kwargs)
  File "C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\matplotlib\tri\tricontour.py", line 280, in tricontour
    return TriContourSet(ax, _args, *_kwargs)
  File "C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\matplotlib\tri\tricontour.py", line 36, in **init**
    ContourSet.**init**(self, ax, _args, *_kwargs)
  File "C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\matplotlib\contour.py", line 780, in **init**
    self._process_args(_args, *_kwargs)
  File "C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\matplotlib\tri\tricontour.py", line 47, in _process_args
    tri, z = self._contour_args(args, kwargs)
  File "C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\matplotlib\tri\tricontour.py", line 82, in _contour_args
    Triangulation.get_from_args_and_kwargs(_args, *_kwargs)
  File "C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\matplotlib\tri\triangulation.py", line 172, in get_from_args_and_kwargs
    triangulation = Triangulation(x, y, triangles, mask)
  File "C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\matplotlib\tri\triangulation.py", line 72, in __init__
    dt = delaunay.Triangulation(self.x, self.y)
  File "C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\matplotlib\delaunay\triangulate.py", line 123, in **init**
    self.hull = self._compute_convex_hull()
  File "C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\matplotlib\delaunay\triangulate.py", line 158, in _compute_convex_hull
    hull.append(edges.pop(hull[-1]))
KeyError: 15630

Python version:
2.7.4 (default, Apr  6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)]

QGIS version:
2.0.1-Dufour Dufour, 34139bc

Python path: ['C:/PROGRA~1/QGISDU~1/apps/qgis/./python/plugins\processing', 'C:/PROGRA~1/QGISDU~1/apps/qgis/./python', 'C:\Users\Steven/.qgis2/python', 'C:\Users\Steven/.qgis2/python/plugins', 'C:/PROGRA~1/QGISDU~1/apps/qgis/./python/plugins', 'C:\PROGRA~1\QGISDU~1\bin\python27.zip', 'C:\PROGRA~1\QGISDU~1\apps\Python27\DLLs', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib\plat-win', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib\lib-tk', 'C:\PROGRA~1\QGISDU~1\bin', 'C:\PROGRA~1\QGISDU~1\apps\Python27', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\PIL', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\win32', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\win32\lib', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\Pythonwin', 'C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode', 'C:\PROGRA~1\QGISDU~1\apps\qgis\python\plugins\fTools\tools', 'F:/Work/12Reuters_25SpringvaleRd_development/data_HO']

**Comment by ccrook** [comment]
Closing stale issue
