### ISSUE TITLE
Error on processing algorithm using the same parameters' name

### ISSUE THREAD

**Issue by gaaraxpo** [ccrook/QGIS-Contour-Plugin#28]
Error when I tried to generate a second contour using the exact same name of parameters including 'InputField' and 'InputLayer'.

This is what I got:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "<string>", line 19, in <module>
  File "/usr/share/qgis/python/plugins/processing/tools/general.py", line 84, in run
    return Processing.runAlgorithm(algOrName, parameters, onFinish, feedback, context)
  File "/usr/share/qgis/python/plugins/processing/core/Processing.py", line 194, in runAlgorithm
    raise QgsProcessingException(msg)
_core.QgsProcessingException: There were errors executing the algorithm.
```

_tried on Ubuntu 18.04_

**Comment by gaaraxpo** [comment]
Oh, I was selecting the 'output' layer. Sorry, my mistake. It works now. Solved.
