### ISSUE TITLE
"Extend filled contour options [optional]" isn't optional

### ISSUE THREAD

**Issue by Geojim** [ccrook/QGIS-Contour-Plugin#48]
Throws errors unless somethings specified, even if not filling contours.

```
Traceback (most recent call last):
File "~/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\contour\ContourGeneratorAlgorithm.py", line 116, in _getEnumValue
id=values[int(id)]
ValueError: invalid literal for int() with base 10: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "~/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\contour\ContourGeneratorAlgorithm.py", line 290, in processAlgorithm
extend = self._getEnumValue( parameters, self.PrmExtendContour, context )
File "C:\Users/jmcguiness/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\contour\ContourGeneratorAlgorithm.py", line 118, in _getEnumValue
raise ContourGeneratorAlgorithmError(
contour.ContourGeneratorAlgorithm.ContourGeneratorAlgorithmError: Invalid value for ExtendOption
```

**Comment by ccrook** [comment]
I've uploaded a potential fix for this issue s version 2.0.12.  I haven't been able to replicate it exactly so not sure where it is coming from.  But I think this should fix it.
