### ISSUE TITLE
Key Error: 4604

### ISSUE THREAD

**Issue by nagellette** [ccrook/QGIS-Contour-Plugin#6]
I get the with the following lines:

An error has occured while executing Python code:

Traceback (most recent call last):
  File "D:\Documents and Settings\tr32014/.qgis2/python/plugins\contour\contour.py", line 373, in accept
    self.makeFilledContours()
  File "D:\Documents and Settings\tr32014/.qgis2/python/plugins\contour\contour.py", line 584, in makeFilledContours
    polygons = self.computeFilledContours( asLayers )
  File "D:\Documents and Settings\tr32014/.qgis2/python/plugins\contour\contour.py", line 651, in computeFilledContours
    self._computeFilledContoursForLevel(levels,extend,polygons)
  File "D:\Documents and Settings\tr32014/.qgis2/python/plugins\contour\contour.py", line 658, in _computeFilledContoursForLevel
    cs = plt.tricontourf(x, y, z, levels, extend=extend)
  File "C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\matplotlib\pyplot.py", line 3108, in tricontourf
    ret = ax.tricontourf(*args, **kwargs)
  File "C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\matplotlib\axes.py", line 8926, in tricontourf
    return mtri.tricontourf(self, *args, **kwargs)
  File "C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\matplotlib\tri\tricontour.py", line 287, in tricontourf
    return TriContourSet(ax, *args, **kwargs)
  File "C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\matplotlib\tri\tricontour.py", line 36, in __init__
    ContourSet.__init__(self, ax, *args, **kwargs)
  File "C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\matplotlib\contour.py", line 780, in __init__
    self._process_args(*args, **kwargs)
  File "C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\matplotlib\tri\tricontour.py", line 47, in _process_args
    tri, z = self._contour_args(args, kwargs)
  File "C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\matplotlib\tri\tricontour.py", line 82, in _contour_args
    Triangulation.get_from_args_and_kwargs(*args, **kwargs)
  File "C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\matplotlib\tri\triangulation.py", line 172, in get_from_args_and_kwargs
    triangulation = Triangulation(x, y, triangles, mask)
  File "C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\matplotlib\tri\triangulation.py", line 72, in __init__
    dt = delaunay.Triangulation(self.x, self.y)
  File "C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\matplotlib\delaunay\triangulate.py", line 123, in __init__
    self.hull = self._compute_convex_hull()
  File "C:\PROGRA~1\QGISDU~1\apps\Python27\lib\site-packages\matplotlib\delaunay\triangulate.py", line 158, in _compute_convex_hull
    hull.append(edges.pop(hull[-1]))
KeyError: 4604

Python version:
2.7.4 (default, Apr  6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)]

QGIS version:
2.0.1-Dufour Dufour, ebebdf3

Python path: ['C:/PROGRA~1/QGISDU~1/apps/qgis/./python/plugins\\processing', 'C:/PROGRA~1/QGISDU~1/apps/qgis/./python', 'D:\\Documents and Settings\\tr32014/.qgis2/python', 'D:\\Documents and Settings\\tr32014/.qgis2/python/plugins', 'C:/PROGRA~1/QGISDU~1/apps/qgis/./python/plugins', 'C:\\PROGRA~1\\QGISDU~1\\bin\\python27.zip', 'C:\\PROGRA~1\\QGISDU~1\\apps\\Python27\\DLLs', 'C:\\PROGRA~1\\QGISDU~1\\apps\\Python27\\lib', 'C:\\PROGRA~1\\QGISDU~1\\apps\\Python27\\lib\\plat-win', 'C:\\PROGRA~1\\QGISDU~1\\apps\\Python27\\lib\\lib-tk', 'C:\\PROGRA~1\\QGISDU~1\\bin', 'C:\\PROGRA~1\\QGISDU~1\\apps\\Python27', 'C:\\PROGRA~1\\QGISDU~1\\apps\\Python27\\lib\\site-packages', 'C:\\PROGRA~1\\QGISDU~1\\apps\\Python27\\lib\\site-packages\\PIL', 'C:\\PROGRA~1\\QGISDU~1\\apps\\Python27\\lib\\site-packages\\win32', 'C:\\PROGRA~1\\QGISDU~1\\apps\\Python27\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~1\\QGISDU~1\\apps\\Python27\\lib\\site-packages\\Pythonwin', 'C:\\PROGRA~1\\QGISDU~1\\apps\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode', 'D:\\Documents and Settings\\tr32014\\.qgis2\\python\\plugins\\mmqgis/forms', 'C:\\PROGRA~1\\QGISDU~1\\apps\\qgis\\python\\plugins\\fTools\\tools']

**Comment by ccrook** [comment]
Closing this issue.  Possibly addressed by point thinning option in plugin?

**Comment by erwanC** [comment]
Indeed, but it's decrease the accuracy badly...
For now, i use another software to export the contour.

thx.

**Comment by ccrook** [comment]
Hi Erwan

The point thinning certainly can decrease the accuracy, either if the radius is set too large, or if the data have points very close together (within the thinning radius) with values to be contoured that are very different.  In this case the contouring algorithm may certainly not give results that are what you want to see.  My point thinning algorithm is certainly a bit simplistic - it discards some values so if they carry significant information then you will lose accuracy as you say.

Glad you've found another way to do this.
